### Импорт необходимых библиотек

In [1]:
import csv
import numpy as np
import pandas as pd
import datetime

### Подготовка и импорт данных

Были взяты данные по деятельности пользователей в системе управления продажами Инвест 2.0. компании АО "ГК "ЭТАЛОН".

#### Описание данных

*al_id* - уникальный идентификатор строки;

*suser_id* - пользователь, выполнивший действие;

*report_id* - ID запущенного отчёта (актуально только для страницы /report.php). Это основные точки входа отчётов;

*al_program* - URI странички без параметров;

*al_m* - используемый метод;                

*al_ip* - IP машины, с которой вызвали обработку;

*al_js* - сессия (объединяющий фактор); 

*al_ef* - выбор нужна ли выгрузка в MS Excel;

*al_url* - URI с параметрами;

*al_get* - содержимое запроса GET;

*al_post* - содержимое запроса POST;

*al_bdt* - время начала выполнения запроса;

*al_edt* - время окончания выполнения запроса;

*al_mt* - длительность выполнения запроса в условных единицах.

In [2]:
filename = 'C:/Users/think/Downloads/Telegram Desktop/2021-001.csv'

In [3]:
def get_rows_in_file(filename):
    rows = [] 
    with open (filename, 'r') as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            fff = []
            if (1 < len(row) <= 3) and (row[1].find('\n')!=-1):
                ff = []
                for i in range(len(row)):
                    d = row[i].split('\n')
                    ff.append(d)
                if len(row) == 3:
                    row = ('').join([ff[0][0],ff[1][0]])
                    fff.append(row)
                    row = ('').join([ff[1][1],ff[2][0]])
                    fff.append(row)
                    rows.append([fff[0]])
                    rows.append([fff[1]])   
                elif len(row) == 2:
                    row = ('').join([ff[0][0],ff[1][0]])
                    fff.append(row)
                    fff.append(ff[1][1])
                    rows.append([fff[0]])
                    rows.append([fff[1]]) 
            elif (len(row) > 3) and ((('').join(row)).find('\n')!=-1):
                row = (('').join(row)).split('\n')
                rows.append([row[0]])
                rows.append([row[1]])
            else:
                rows.append(row)   
    for i in range(len(rows)):
        if len(rows[i]) == 1:
            rows[i][0] = rows[i][0].split('~')
        elif len(rows[i]) == 2:
            rows[i] = (('').join([rows[i][0],rows[i][1]])).split('~')
        elif len(rows[i]) > 2:
            rows[i] = (('').join(rows[i])).split('~')
    for i in range(len(rows)):
        rows[i] = np.array(rows[i]).flatten().tolist()
    return rows

In [4]:
data = pd.DataFrame(get_rows_in_file(filename), columns = ['al_id', 'suser_id', 'report_id', 'al_program', 'al_m', 'al_ip', 'al_js', 
                                     'al_ef', 'al_url', 'al_get', 'al_post', 'al_bdt', 'al_edt', 'al_mt'])
data['al_bdt'] = pd.to_datetime(data['al_bdt']) 
data['al_edt'] = pd.to_datetime(data['al_edt'])
data['suser_id'] = data['suser_id'].astype(np.int64)
data['report_id'] = data['report_id'].astype(np.int64)
data['al_mt'] = data['al_mt'].astype(np.int64)
data.head()

,al_id,suser_id,report_id,al_program,al_m,al_ip,al_js,al_ef,al_url,al_get,al_post,al_bdt,al_edt,al_mt
0,1,2,9,/index.php,GET,172.16.131.59,b-585899cc46e8e2eb03f6b977031bd5,0,/,"'a:2:{s:12:""HTTP_REFERER"";N;s:10:""USER_AGENT"";...",a:0:{},2021-01-01 00:02:24,2021-01-01 00:02:24,1
1,2,2,9,/index.php,GET,172.16.128.27,9-20823ce170edccb8ed6622606427a4,0,/,"a:2:{s:12:""HTTP_REFERER"";N;s:10:""USER_AGENT"";N;}",a:0:{},2021-01-01 00:06:00,2021-01-01 00:06:00,1
2,3,2,9,/index.php,GET,172.16.131.59,e-849fe2c4eb8fb21481c575daa710f1,0,/,"'a:2:{s:12:""HTTP_REFERER"";N;s:10:""USER_AGENT"";...",a:0:{},2021-01-01 00:07:24,2021-01-01 00:07:24,1
3,4,2,9,/index.php,GET,172.16.131.59,f-a4890a218b8e39eb8c4f22da17840d,0,/,"'a:2:{s:12:""HTTP_REFERER"";N;s:10:""USER_AGENT"";...",a:0:{},2021-01-01 00:12:24,2021-01-01 00:12:24,1
4,5,2,9,/index.php,GET,172.16.128.27,9-418053d03732df2e2232efec463478,0,/,"a:2:{s:12:""HTTP_REFERER"";N;s:10:""USER_AGENT"";N;}",a:0:{},2021-01-01 00:16:56,2021-01-01 00:16:56,1

Сохраняем новую таблицу в Excel:

In [7]:
data.to_csv('data.csv')